---

- name: hacklab.local member server configuration
  hosts: workstations

  roles:
    - { role: commonwkstn }

  tasks:

  - name: Set configure dns
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - 192.168.200.10
      log_path: C:\dns_log.txt

  - name: Ensure directory structure for public share exists
    win_file:
      path: C:\shares\public
      state: directory

  - name: Ensure public share exists
    win_share:
      name: public
      description: Basic RW share for all domain users
      path: C:\shares\public
      list: yes
      full: Administrators
      change: Users

  - name: add windows 10 workstation to hacklab.cocal
    win_domain_membership:
      dns_domain_name: hacklab.local
      domain_admin_user: test_admin@hacklab.local
      domain_admin_password: AutomationDoesW0rk!
      state: domain
    register: domain_state

  - name: reboot workstation if needed
    win_reboot:
    when: domain_state.reboot_required
